input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "job" => "nutrialianza"
    }

    remove_field => [
      "agent",
      "ecs",
      "host",
      "input",
      "@version"
    ]
  }
}

output {
  loki {
    url => "http://loki:3100/loki/api/v1/push"
  }
}
